### ISSUE TITLE
Can't quit demo example (no menu, closing main window doesn't kill app)

### ISSUE THREAD

**Issue by DevulderJeanPaul** [bibinjacobpulickal/AppKit-Cocoa-Resizable-NSView#1]
Hi,
Please add this for quit example code when closing window

    func applicationShouldTerminateAfterLastWindowClosed(_ sender: NSApplication) -> Bool
    {
        return true
    }

Thanks,

**Comment by bibinjacobpulickal** [comment]
Thanks for noticing this issue. I've pushed the fix to master branch. PS: Closing this issue.
